### ISSUE TITLE
Phase 5 : I need to be able to facilitate communication amongst all of the adapters loaded into the QEM detector system. 

### ISSUE THREAD

**Issue by SophieKSTFC** [stfc-aeg/qemii-detector#23]
Acceptance Criteria : 

- [ ] Inter adapter communication is used to register which adapters have been loaded into the QEM system. Each adapter can be interrogated via their parameter tree by the QEM-Detector adapter.

**Comment by ANeaves** [comment]
IAC is now used to communicate between different loaded adapters as required
